### DISCUSSION TITLE
New Ecoflow Wifi Firmware is re-opening ports, so this integration is active again as of February 2023

### DISCUSSION THREAD

**Discussion by DarrylGNOLA** [vwt12eh8/hassio-ecoflow#67] [General]
I know this info has been written in other threads, but I wanted to make this a new heading to make information obvious. 

With my Delta Pro the newest Wifi firmware of **V3.0.2.21** has reopened the TCP port and this integration works once again. Maybe it is time to continue on the beta versions.

**Comment by claudeju** [comment]
I also hope that there will be a new version soon

**Comment by DarrylGNOLA** [comment]
@claudeju Are you not seeing the Wifi update V3.0.2.21? or do you wish there was a newer version than this one?

**Reply by tronron** [reply]
My Delta Pro's are at FW 3.0.1.11 and 3.0.2.25 is offered as an upgrade. Is it likely this integration will work again if I upgrade? I am afraid to upgrade without prior confirmation, as I rely on using the official API from Ecoflow to read SOC and I'm concerned any upgrade might break it. Without being able to read battery SOC, my solar system and all my Ecoflow units are worthless.

**Comment by bluefire100** [comment]
> n

How can I get this firmware? I'm on v3.0.1.11 and my DP is not showing any updates available? And this integration is not working with my DP after entering IP address; just nothing happens.

**Comment by DarrylGNOLA** [comment]
@bluefire100 It seems some people have contacted Ecoflow support and their serial number added to a list of units to accept the Wifi update. I know support wrote something similar to me and @Roughman007 had said his update showed up after contacting support.

Let us know if it works for you.

**Comment by Patrick762** [comment]
I also contacted the Ecoflow support and after that the firmware was available (River Max, WiFi 3.0.1.11).

And even if it doesn't work with this integration, after you got the api key, you can also use the API as rest sensor like this:

```yaml
rest:
- scan_interval: 20
    resource: https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=[DEVICE SN]
    headers:
      appKey: [KEY FROM SUPPORT]
      secretKey: [KEY FROM SUPPORT]
      User-Agent: Home Assistant
    binary_sensor:
      - name: "River Max Online"
        value_template: "{{ value_json.code == '0' }}"
    sensor:
      - name: "River Max Charge"
        value_template: "{% if value_json.code == '0' %}{{ value_json.data.soc|float }}{% else %}unavailable{% endif %}"
        device_class: battery
        unit_of_measurement: '%'
      - name: "River Max Remaining Time"
        value_template: "{% if value_json.code == '0' %}{{ value_json.data.remainTime|float }}{% else %}unavailable{% endif %}"
        unit_of_measurement: 's'
      - name: "River Max Output Power"
        value_template: "{% if value_json.code == '0' %}{{ value_json.data.wattsOutSum|float }}{% else %}unavailable{% endif %}"
        device_class: power
        unit_of_measurement: 'W'
      - name: "River Max Input Power"
        value_template: "{% if value_json.code == '0' %}{{ value_json.data.wattsInSum|float }}{% else %}unavailable{% endif %}"
        device_class: power
        unit_of_measurement: 'W'
```
