### DISCUSSION TITLE
Integration with existing domestic solar using Glow CAD for automated charging help

### DISCUSSION THREAD

**Discussion by Maxctran** [vwt12eh8/hassio-ecoflow#75] [General]
Thanks to a lot of Youtube tutorials @mattwells and help from  @Ne0-Hack3r giving access to his SHP integration I now have my Smart Home Panel and 2 Delta Pros and extra batteries hooked up and controllable via Home Assistant. I also managed to get a Glow CAD smart meter device that I have managed to connect to HA as well. 

The aim for this is because I have existing solar array on my roof which is fed into their own inverters so produce AC power for the house. I want any excess solar to charge into the Delta Pros via the Smart Home Panel. However this is where I have become stuck again... I know I really only need 5 entities to work in harmony (anonymised):

Smart Meter Electricity:FXXXX Power – sensor.smart_meter_electricity_fXXXX_power
SHP PRO1 Recharge – switch.shp_pro1_recharge
SHP PRO2 Recharge - switch.shp_pro1_recharge
Delta Pro 1 charge speed – number.delta_pro_1_ac_charge_speed
Delta Pro 2 charge speed - number.delta_pro_2_ac_charge_speed

So you should know that it starts at 200w charge rate, so I have managed to get the first sequence working which once Smart Meter is showing '-200 (watts)' or less it turns the 1st turns on recharge for 1st Delta Pro and makes sure its set to 200w. 

`alias: basic toggle test
description: ""
trigger:
  - platform: numeric_state
      entity_id: sensor.smart_meter_electricity_fXXXX_power
    below: -200
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shp_pro1_recharge
  - service: number.set_value
    data:
      value: "200"
    target:
      entity_id: number.delta_pro_1_ac_charge_speed`

However the next step I seem to be not getting anywhere. If the power sensor continues to stay at -100 or more after it refreshes then the Delta Pro charge speed needs to keep going up in 100w until 1500w (this is a cap I have found EcoFlow has put on the Delta Pro if it registered DC charge as I have both of them connected to separate solar panels via the DC cable so I can't charge to 2900w). 

So I was trying to work out how to do this and ended up asking ChatGPT on Bing as I read it can do basic coding and it came up with this:

`alias: Ecoflow Delta Pro Charge Control
icon: mdi:battery-charging
description: Adjust the charge speed of Ecoflow Delta Pro based on the power reading sensor
variables:
  power_sensor: sensor.power_reading # change this to your power reading sensor entity ID
  ecoflow_entity: switch.ecoflow_delta_pro # change this to your Ecoflow Delta Pro entity ID
  min_charge_speed: 200 # the minimum charge speed in watts
  max_charge_speed: 1500 # the maximum charge speed in watts
  charge_step: 100 # the amount to increase or decrease the charge speed by in watts
  power_threshold: -200 # the power reading threshold to start adjusting the charge speed in watts
trigger:
  - platform: state
    entity_id: "{{ power_sensor }}"
action:
  - choose:
      - conditions: "{{ trigger.to_state.state | int < power_threshold }}"
        sequence:
          - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
            target:
              entity_id: "{{ ecoflow_entity }}"
            data:
              speed: >-
                {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                {% set new_speed = current_speed + charge_step %}
                {{ [new_speed, max_charge_speed] | min }}
      - conditions: "{{ trigger.to_state.state | int > 0 }}"
        sequence:
          - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
            target:
              entity_id: "{{ ecoflow_entity }}"
            data:
              speed: >-
                {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                {% set new_speed = current_speed - charge_step %}
                {{ [new_speed, min_charge_speed] | max }}`

So I tried to add it and kept getting errors whereever I paste it e.g. in automations.yaml
![image](https://user-images.githubusercontent.com/129412233/235359518-3e925ed0-0621-4ed3-aabb-0508623c8318.png)

Trying to paste into new automation via edit in YAML comes up with this error
![image](https://user-images.githubusercontent.com/129412233/235359326-94761484-798c-4f3f-ac59-2b43d74784cd.png)

I checked the code in a YAML validator and it seems to not spot any errors so I think its just I'm putting it in the wrong place? Any help with the script code or what I am doing wrong with the autogenerated code above would be great.

**Comment by mattwells** [comment]
I am not familiar enough to know if the YAML you have will work or not but I can see that the indentation (the number of spaces at the start of each line) has gone a little wonky. This indentation is really important to YAML as it defines if the next line is a child or sibling of the previous one. Take for example the line that starts with ` service: ecoflow.set_charge_speed`, with the YAML in provided there is a sibling called `target` which is expecting a child called `entity_id`. However the indentation in YAML rules is the same level as the `target` so it becomes a sibling rather than the child that was intended.

I am sorry if this doesn't mean all that much to you but the indentation is the the grammer in YAML and if the grammer is not correct the computer can't understand it. Sadly computers are not as capable at guessing what a human means when we forget to put punctation in our sentenses.

Anyway I don't know if this is correct but I believe that I have corrected the YAML for you, however I have had a go at correcting it for you, it may or may not work.

```yaml
automation:
- alias: "Ecoflow Delta Pro Charge Control"
  icon: mdi:battery-charging
  description: Adjust the charge speed of Ecoflow Delta Pro based on the power reading sensor
  variables:
    power_sensor: sensor.power_reading # change this to your power reading sensor entity ID
    ecoflow_entity: switch.ecoflow_delta_pro # change this to your Ecoflow Delta Pro entity ID
    min_charge_speed: 200 # the minimum charge speed in watts
    max_charge_speed: 1500 # the maximum charge speed in watts
    charge_step: 100 # the amount to increase or decrease the charge speed by in watts
    power_threshold: -200 # the power reading threshold to start adjusting the charge speed in watts
  trigger:
    - platform: state
      entity_id: "{{ power_sensor }}"
      action:
        - choose:
          - conditions: "{{ trigger.to_state.state | int < power_threshold }}"
            sequence:
            - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
              target:
                entity_id: "{{ ecoflow_entity }}"
              data:
                speed: >-
                  {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                  {% set new_speed = current_speed + charge_step %}
                  {{ [new_speed, max_charge_speed] | min }}
          - conditions: "{{ trigger.to_state.state | int > 0 }}"
            sequence:
            
            - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
              target:
                entity_id: "{{ ecoflow_entity }}"
              data:
                speed: >-
                  {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                  {% set new_speed = current_speed - charge_step %}
                  {{ [new_speed, min_charge_speed] | max }}
```

I might have to look into this some more, I can see some cool things I might be able to do to use excess solar power when my delta pro battery is full...

**Reply by Ne0-Hack3r** [reply]
> This indentation is really important to YAML

Yup. I learned that real quick as I dove into HA in the first place. And now I'm learning it even more as I dive into Python. I've used a number of scripting languages over the years but Python/YAML are the first structures I've encountered where the indentation is so critical.

I'm used to code blocks that start and end:
```
While ($True) { write-host "Hello World!" }
```
In Power shell that can be:
```
While ($True) do {
Write-Host "Hello World"
}
```
or
```
While ($True)
{
    write-host "Hello World!"
}
```

But Python wants:
```
while True:
  print("Hello World")
```
must be small w and capital T and 'print' (in lower case) but be indented under the 'while' statement

YAML follows the same strict indention and case sensitivity.

**Reply by Maxctran** [reply]
@mattwells 

Sorry I couldn't work out how to post code on the forum (thats how much this is all new to me!) I think I have finally worked it out so my working basic toggle looks like this

```
alias: basic toggle
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.smart_meter_electricity_f0000_power
    below: -200
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shp_pro1_recharge
  - service: number.set_value
    data:
      value: "200"
    target:
      entity_id: number.delta_pro_1_ac_charge_speed
mode: single
```
So the ChatGPT code actually looks like this:
```
alias: Ecoflow Delta Pro Charge Control
icon: mdi:battery-charging
description: Adjust the charge speed of Ecoflow Delta Pro based on the power reading sensor
variables:
  power_sensor: sensor.power_reading # change this to your power reading sensor entity ID
  ecoflow_entity: switch.ecoflow_delta_pro # change this to your Ecoflow Delta Pro entity ID
  min_charge_speed: 200 # the minimum charge speed in watts
  max_charge_speed: 1500 # the maximum charge speed in watts
  charge_step: 100 # the amount to increase or decrease the charge speed by in watts
  power_threshold: -200 # the power reading threshold to start adjusting the charge speed in watts
trigger:
  - platform: state
    entity_id: "{{ power_sensor }}"
action:
  - choose:
      - conditions: "{{ trigger.to_state.state | int < power_threshold }}"
        sequence:
          - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
            target:
              entity_id: "{{ ecoflow_entity }}"
            data:
              speed: >-
                {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                {% set new_speed = current_speed + charge_step %}
                {{ [new_speed, max_charge_speed] | min }}
      - conditions: "{{ trigger.to_state.state | int > 0 }}"
        sequence:
          - service: ecoflow.set_charge_speed # change this to the service that sets the charge speed of Ecoflow Delta Pro
            target:
              entity_id: "{{ ecoflow_entity }}"
            data:
              speed: >-
                {% set current_speed = state_attr(ecoflow_entity, 'charge_speed') | int %}
                {% set new_speed = current_speed - charge_step %}
                {{ [new_speed, min_charge_speed] | max }}
```

So I think that is the same as what your looks like but I am not sure if the indents etc are different. Anyways I guess my main question was **how** or **where** am I pasting the custom code if I am I not creating it using the visual editor in automations, if I am pasting it in Edit in YAML it doesn't seem to like it (including what you posted) so I must be doing something wrong. When I check in File Explorer in the automation.yaml each automation has a id number do I need to work out what that is first? I'm still fumbling around and trying to get my around the errors...

**Comment by Ne0-Hack3r** [comment]
I don't have examples to share at this point in time though I am planning to build out some automations that control when circuits are switched to battery on the SHP based on solar input to the DPs and possibly even try to find a way to "fool" the SHP into switching between DPs (for a form of "load balancing") under certain conditions. All of that is going to take some time and thought to build out and test and I've been waiting for the weather to reach a point where I have reliable enough solar to work with.

That said, you might have a look at this:
https://community.home-assistant.io/t/optimizing-use-of-unused-solar-power-to-charge-a-tesla/340818

It's not exactly the same thing but a similar concept and give some good example of more complex automation. In particular I would suggest considering the 'for' condition for the same reasons the author suggests in the YAML comments. You don't want things to be jumping around going up and down all the time so it might be prudent to automate such that "once export is -200W for 1 minute... start charging" or "if export -500W for 30 seconds, change charge rate..." (again, this is off the cuff thoughts not really thinking through all the details). Another random thought might be to try to construct a single automation that can dynamically adjust. Something like "whenever export rate changes by <-100W (for >30 seconds), turn charging "on" and set rate to {export-rate} x 0.9 [rounded to the nearest 100]". Making your charge rate a rounded percentage of the export rate would likely make it easier to do what you want in only 1 or 2 automations as opposed to creating a separate automation for every 100W "step" and I'd suggest that having the charge rate be something a bit less than the export rate would give you a bit of buffer to be sure you're always charging with "excess energy".

Other consideration are making sure you don't create some kind of infinite loop, thinking through if/when/how you want to end the charging (set the charging switch to OFF) taking into account that SHP will flip that off itself if the DP ever hits the charge limit.

You could consider a much simpler approach such as determining a good average charge rate, setting the DP to that, and simply having the automation flip the charging switch "on" whenever export is available (for >1 minute) and "off" whenever it is not (for >1 min). For example: Let's say that you generally export 10kwh (or more) over a 5 hour period on a daily basis and you know you can fill the DP from empty in 4 hours at 1000W -- so you just set the DP to 1000W rate and let the charge switch be "on" anytime power is -11000W and "off" otherwise. Perhaps not as intelligent or sophisticated but might get you 90% of what you want with 10% of the work.

You may also want to think about cloudy days or days with high demand where you did not export enough to charge the DP enough "for free". Maybe that means you just don't get much, if any run time out of the battery that cycle. Maybe you want to be sure the battery never goes below X% -- In any case there may be merit to leveraging the SHP automations for some things and only use HA for stuff the SHP can't do. For example a simple automation within the SHP could say "between 1 and 4am daily, if the battery is <55%, charge to 60% at 900W" (if you want to use AC charging to top up against a buffer for example).

Apologies if all this is not helpful (I know I may be just injecting more to think about). The trick with automation is to work through the complexity back to the simplest way to accomplish the intended result. Sometimes this can be limited by the tools at hand and other times it just takes an iterative process. On the other hand when wading into new territory it is sometimes best to start as simply as possibly and slowly add functionality from there. You may find it gets overly convoluted in the end and you may end up (with hindsight and new found knowledge) starting over and making something more elegant, powerful, and yet simpler. But that's all part of the journey. ;)

**Comment by Ne0-Hack3r** [comment]
@Maxctran 

> However the next step I seem to be not getting anywhere. If the power sensor continues to stay at -100 or more after it refreshes then the Delta Pro charge speed needs to keep going up in 100w until 1500w (this is a cap I have found EcoFlow has put on the Delta Pro if it registered DC charge as I have both of them connected to separate solar panels via the DC cable so I can't charge to 2900w).

What is this 1500W cap you speak of? The limit for manual AC charging via SHP is the same as for plugging a DP into the wall when not connected to SHP. It's a 15A limit (so 1800W assuming 120V exactly from the wall) but you will never see the full 1800W going into the battery due to conversion losses and the inverter will ramp down based on battery temp and how full the battery is as well.

You can achieve up to 3400W rapid AC charging via SHP using a native SHP charging automation. Those can be manipulated using JSON/MQTT as well but that would not be 'simple' within an HA automation given the structure of it. I've done it to create a charging automation that has a -20% starting point (which can be set in the JSON but is not accessible via the app) but that was done by manually manipulating the payload and not via HA automation.

One thing I've been contemplating (but have not had time to test) is setting up an automation within the SHP and using triggers in HA to simple enable or disable that automation. I want to be sure this can be done without posting the entire content of every variable within the automation config back to the SHP each time, however.

**Reply by Maxctran** [reply]
@Ne0-Hack3r 

Sorry for the delay getting back to you when your coming back so quickly, I work and look after my daughter so usually too busy in the day and so exhausted I am passing out when my daughter does till the morning reset of they next day!

So basically the 1500w charging cap is relating to EcoFlow apparently trying to protect the Delta Pro (DP) against overall charging rate being exceeded (according to Ecoflow's customer service after a long string of questions about it). So you know that DP accepts solar panels directly plugged in through its built in inverter so it converts the DC to AC to charge it. Well I have 2 DPs and I have attached them to Smart Home Panel (SHP). However I don't just have my existing rooftop solar which feeds the house and SHP with AC charge. Since I installed the 2 DPs I have installed 2 permanent tiny solar arrays in my garden which attach to each DP via each solar charging port. 

So the long and short of it is when it detects a charge from the solar panels attached directly it won't allow you to charge over 1500w on each DP on the AC charge from SHP. When its night time or pitch black (aka when absolutely no solar voltage is detected on the additional solar panels) or if I manually unplug it in the daytime, I can charge each DP at 3400w via SHP with no issues. I have complained to EcoFlow saying this is ridiculous as it should just be smart enough to cap the overall charge instead it is assuming any charge is dangerous and going to charge it too quickly. The cap means even if the directly connected solar is just producing 10w then the 1500w cap comes in, so if my rooftop solar is producing 1700w excess I still have to split it between the 2 DPs (1500w and 200w). 

So automation is hopefully my saviour from spending all day juggling where the rooftop solar is going and at what rate etc. I am sure I will get there in the end I just think I will need a lot of guidance along the way...

**Reply by Ne0-Hack3r** [reply]
I don’t know what support person you’re talking to but that sounds like BS to me. First off the solar input comes through an MPPT controller at a max of 1600W DC to DC and has nothing to do with the AC/DC inverter which can charge or discharge (but not both at the same time). The DP is capable of 6500W of total multi charge input and the infinity port/cable is rated for >3000W sustained for 3 hours continuous. And my info is direct from specs and confirmed by an actual engineer in R&D. If they changed that behavior in firmware it’s either a bug or an intentional change they said nothing about in update notes. The max solar input is 1600W and the max AC is 1800W (120V), 2800W (240V) or 3400W via infinity port. Solar, AC, and Smart Gen (via DC into EB port) at up to 1600W can all be combined to provide up to 6500W of simultaneous charging. I don’t have SG but have tested AC + Solar plenty of times. So I’m calling BS or bug until proven otherwise.

**Reply by Maxctran** [reply]
I get exactly what your saying and I think it's a bug too rather than a hardware limitation. However it's something I've not been able to get around when using the Android EcoFlow app. I will try to do a video of it on my phone to show you what I mean. Until they sort it the automation I'm setting up is working around it so the 1500w charge cap is there but it would be super easy to alter the cap in automation once it's gone to charge to 3400w.

**Reply by Ne0-Hack3r** [reply]
I just did a 3400W AC charge via automation while I had 300-400W solar coming in and got combined charge... I didn't try via manual charging but that is limited to 1800W max (still should get that plus up to 1600W solar combined). In any case there have not been any firmware updates in a while and unless you're on the briefly release .19 update there have not been any SHP firmware changes in 8+ months. When controlling SHP via HA you're going direct with no app involved so I'm still a bit confused by the behavior you describe... That said, I'm not running .19 (which was pulled shortly after release and is no longer available).

**Reply by Maxctran** [reply]
Thanks i didn't realise the automation in app allows it to charge beyond 1500w when set on SHP. I had presumed the same thing would happen and it will not charge beyond 1500w. I've just tried it and it worked. I'll try and record the 1500w bug video still I was trying to explain. I think my goal will still be the same to get each DP to charge to 1500w each if I am generating 3kw of excess solar so they can charge evenly to minimalise the charge cycles long term. Is there a way of accessing the automation settings on SHP home assistant entities as it might be something to tweak once I get the automation running in its first attempt.

**Reply by Ne0-Hack3r** [reply]
Yes. The SHP automations are part of the JSON payloads posted to MQTT and can be modified and posted back to ../set -- they are a bit complex and I have not taken the time to think about how to manipulate them via a dashboard or HA automation. These are also exposed in the beta API via signed HTTP calls or MQTT so I assume Ecoflow is okay with developers playing with that externally (eventually, once the API is public, and only within the rules of the API). Bare in mind that you're playing with MQTT by having HA "impersonate" the mobile app so "be careful" and don't be surprised if something breaks after some update down the road...

The main concern I have is if only "part" of an SHP automation can be changed without having to first get the whole thing, alter just the value(s) desired, and then post the whole thing back to ../set -- I've done the latter manually using MQTT Explorer to modify an SHP recharge automation so it would charge to 100% after dropping to 80% -- the app does not expose the drop threshold but instead hard codes it to target - 5% (100-5=95) but the SHP itself is happy with whatever value you give it...

**Comment by Maxctran** [comment]
Heres a brief video which shows the 1500w on 1 DP. https://youtu.be/2ODFkvVX2Ag

**Reply by Ne0-Hack3r** [reply]
Looks like you have a 220-240V unit outside the USA which is why you can set >1800W for custom charging rate... For USA units the app caps it at 1800W because of the 15A max current capacity of that input (15Ax120V=1800W). I believe the ~240V units are capped at ~12A because many circuits in other countries are 13A which is why the cap is 2800W for these units. The inverter is 120/240 and I've charged my North American unit from 240V. In this case the 120V outlets on the front are disabled. Early versions of the app detected 240V input and would switch to allow selection >1800W even on the 120/240V units but later versions simply cap it at 1800W with the only way to charge faster being via SHP (which in North America means using 30A/120V circuits for each DP to achieve >3000W charge).

What you are seeing may actually be a firmware issue in the DP itself (and there have been a couple of recent firmware updates there). Using manual charging from the SHP is much like plugging the DP into the wall (except the charge comes via the infinity cable) in that the custom/fast switch and charging rate set in the app (on the DP) controls. When using a recharge automation the settings on DP are overridden by the SHP and the settings in the recharge automation apply (as long as the switch on the DP is in 'fast' position). If the switch is in "custom" even an automation follows the custom charge rate (though charge/discharge limits and charging targets are governed by the SHP).

I would push back on support because you should easily be able to do AC charging at full rate (1800/2800W depending on unit and 120/240 supply) while charging at 1600W (max) via solar. I've certainly done it before, in testing, though it is not a common thing for me to AC charge while solar is available via DC. The main thing I could see using it for is a rapid charge from grid to top up quickly if a storm or some such was imminent.

**Comment by Maxctran** [comment]
@Ne0-Hack3r 

OK after a bit of playing in the app I've worked out the easiest way to bypass the weird 1500w is by setting 2 separate automations for each DP to recharge at 3400w. Now I just need to manually turn each automation on for each DP and it allows me to alter the charge speed on each DP manually like I showed in the video but it will go beyond 1500w to up to 2900w so **thanks a lot** for pointing it out as it has been a big bug bear since I had them installed!

So if I could toggle those 2 automations on/off in home assistant script it would allow me to charge each DP beyond 1500w. But it sounds like that is something that much more complex and I'm still trying to work out the basic automation script and not getting very far so far. I still can't get ChatGPT coding lines to actually do what it's supposedly should do. I've worked out if I use the Visual Editor mode and replicate the script conditions that ChatGPT (as best I can work out) then put a generic number (into the charge speed value) in and save it then paste in the line of code that ChatGPT produced it's stopped the error messages that I originally posted but when I run the script it aborts before it gets there. As I said in earlier post it's really difficult to find a decent amount of time to focus on it to make a difference.

I am currently able to get automation script to start when power reading is -200w then it turns on first DP and sets the charge speed to 200w. I have managed this morning to get the charge speed to increase by 100w while the power reading stays under 100 all the way to 1500w cap.

I am trying to get it to now reduce the charge speed when its above 0 then it decreases the charge speed by 100w from whatever charge speed it was up to until its back to 200w charge speed then turns the charging off completely. The power reading seems to only update every 10 seconds or so so there needs to be a delay in changing the charge speed up or down or else it will be over/undercharging too much before the next power sensor reading is updated.

So my own attempt basically has gone like this:
When power sensor is -200 switch on DP charge on SHP then set charge speed to 200w
Then 'Choose' between 2 conditions:
1st condition 'while' power reading below -100
Change charge speed to 300w, delay 10 seconds, change charge speed to 400w and delay 10 seconds and so forth to 1500w. Then repeat until power sensor is above 0.
2nd condition 'while' power reading above 0
Change charge speed to 1400w, delay 10 seconds, change charge speed to 1300w and delay 10 seconds and so forth to 200w then turn off DP1.

As I don't get how to write this in a shorter sequence on visual editor, I've just duplicated the same thing and just changed the charge rate for each so the code it ridiculously long and repetitive. However testing it it only works to gradually increase the charge rate from 200w to 1500w but doesn't seem to decrease the charge. I don't know what I am doing wrong yet in the sequence. I am sure I will keep fiddling with it and get mini breakthroughs but any help if I am doing something obviously wrong would be great as usual!

```alias: DP automation
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.smart_meter_electricity_f_power
    below: -200
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shp_pro1_recharge
  - service: number.set_value
    data:
      value: "200"
    target:
      entity_id: number.delta_pro_1_ac_charge_speed
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.smart_meter_electricity_f_power
            below: -100
        sequence:
          - repeat:
              while:
                - condition: numeric_state
                  entity_id: sensor.smart_meter_electricity_f_power
                  below: -100
              sequence:
                - service: number.set_value
                  data:
                    value: "300"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "400"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "500"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "600"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "700"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "800"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "900"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1000"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1100"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1200"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1300"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1400"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1500"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - repeat:
                    until:
                      - condition: numeric_state
                        entity_id: sensor.smart_meter_electricity_f_power
                        above: 0
                    sequence: []
      - conditions:
          - condition: numeric_state
            entity_id: sensor.smart_meter_electricity_f_power
            above: 0
        sequence:
          - repeat:
              while:
                - condition: numeric_state
                  entity_id: sensor.smart_meter_electricity_f_power
                  above: 0
              sequence:
                - service: number.set_value
                  data:
                    value: "1400"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1300"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1200"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1100"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "1000"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "900"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "800"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "700"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "600"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "500"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "400"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "300"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 10
                    milliseconds: 0
                - service: number.set_value
                  data:
                    value: "200"
                  target:
                    entity_id: number.delta_pro_1_ac_charge_speed
                - service: switch.turn_off
                  data: {}
                  target:
                    entity_id: switch.shp_pro1_recharge
mode: single

**Comment by Ne0-Hack3r** [comment]
I think you want to build an automation that is based more on "relative calculation" such as "when meter power below -100 for 1 minute make charge rate [meter] x -1" (or maybe even -0.9 to be safe). You can employ rounding to nearest 100 if you like but I'm pretty sure the DP will take any valid value so you really just need to round to a whole number... You may want to employ "conditions" as well to make sure something does not go off the rails...

Here is an example. It does something different than what you're trying to achieve but maybe it helps illustrate a bit:

```
alias: SHP Load Balance
description: SHP Load Balance
trigger:
  - platform: template
    value_template: |
      {% set soc1 = int(states('sensor.pro1_ems_soc'))    %}
      {% set soc2 = int(states('sensor.pro2_ems_soc'))    %}
      {% set socd = (soc1 - soc2) | abs | round(0)        %}
      {{(socd >= 10)}}
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition:
  - condition: template
    value_template: |-
      {% set out1 = states('sensor.pro1_ac_output_power') %}
      {% set out2 = states('sensor.pro2_ac_output_power') %}
      {% set on1  = (int(out1) > 0 and int(out2) <= 0)    %}
      {% set on2  = (int(out2) > 0 and int(out1) <= 0)    %}
      {{(on1 or on2)}}
  - condition: numeric_state
    entity_id: sensor.shp_all_pro_output
    above: 650
    below: 1800
  - condition: numeric_state
    entity_id: sensor.delta2_soc
    above: 5
    below: 95
action:
  - service: number.set_value
    target:
      entity_id: number.delta2_charge_limit
    data:
      value: "{{ states('sensor.delta2_soc') | float | round(0) + 2 }}"
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: number.delta2_charge_limit
    data:
      value: "{{ states('sensor.delta2_soc') | float | round(0) - 2 }}"
mode: single
```

This is what I use to 'fool' the SHP into a form of load balancing. It watches for >10% difference in average SOC between my 2 sets of DP+EB and then switches my D2 charging on at 1200W for 1 minute by setting the charge limit to [current SOC] +2% then setting back to -2% below SOC... It only does this if the D2 SOC is >5% and <95%, only 1 DP is supplying power, and the output from that DP is >650W and <1800W

I'm using my D2 as a "dummy load" to artificially push the demand >1800W... This causes the SHP to engage the 2nd DP and then, 1 minute later, if demands is <1200W the DP with lower SOC will disengage... Note that I'm only using sensors from the DPs (nothing from SHP) and will eventually use a smart switch with a 1000W of halogen or some other dummy load. The D2 made for an easy "proof of concept".

Hopefully that helps?
