### ISSUE TITLE
Support for Delta 2

### ISSUE THREAD

**Issue by maltetgh** [vwt12eh8/hassio-ecoflow#59]
Hi,

are there any plans/timeline to support Ecoflow Delta 2?

Is there anything I can help with (I have one).

Thank you :)

**Comment by emmvaueff** [comment]
I also have a Delta 2 with additional battery device and need to use this cool integration.
@vwt12eh8 Let me know, if I can help

**Comment by replayfactory** [comment]
+1 for this !
Tell me if I can help, my delta 2 is on his way.

**Comment by Ne0-Hack3r** [comment]
+1 here as well... Just got a Delta 2 and would also be willing to help/test/etc.

**Comment by Cricri6799** [comment]
+1 again. 
Waiting for the next realease contains DELTA 2 maybe ...

**Comment by onkelcommy** [comment]
+1 Just got my Delta 2 today!

**Comment by bozman2021** [comment]
+1

**Comment by nerra0pos** [comment]
+1 from me

**Comment by nxxxse** [comment]
Instead of spamming with +1 could one who already has the Delta 2 on hand test if 8055/tcp is only open in IOT mode or also when the device is connected to an access point? Please state your firmware version and whether it is the latest fw. I would be interested if the local API has also been "locked down" on the Delta 2, same as with the other Deltas. #60

**Comment by Cricri6799** [comment]
> Instead of spamming with +1 could one who already has the Delta 2 on hand test if 8055/tcp is only open in IOT mode or also when the device is connected to an access point? Please state your firmware version and whether it is the latest fw. I would be interested if the local API has also been "locked down" on the Delta 2, same as with the other Deltas. #60

Delta 2 IOT is always on, no button, and all TCP ports are closed

**Comment by Otherbright** [comment]
> Instead of spamming with +1 could one who already has the Delta 2 on hand test if 8055/tcp is only open in IOT mode or also when the device is connected to an access point? Please state your firmware version and whether it is the latest fw. I would be interested if the local API has also been "locked down" on the Delta 2, same as with the other Deltas. #60

If you think there is a way to bypass the restrictions of the latest Delta 2 update, I can try to get one to work on.

**Comment by Ne0-Hack3r** [comment]
> > Instead of spamming with +1 could one who already has the Delta 2 on hand test if 8055/tcp is only open in IOT mode or also when the device is connected to an access point? Please state your firmware version and whether it is the latest fw. I would be interested if the local API has also been "locked down" on the Delta 2, same as with the other Deltas. #60
> 
> Delta 2 IOT is always on, no button, and all TCP ports are closed

Confirmed. With Delta Pro I can telnet to 8055 and get a stream of data. With Delta 2, I cannot.

**Comment by EasyEl** [comment]
Sadly I let their support know that I'll return my new Delta Pro as they have chosen to close the comms port. For me it is vital to get/send data from the unit. Without it any integration is kind of crude.

**Comment by Otherbright** [comment]
> Sadly I let their support know that I'll return my new Delta Pro as they have chosen to close the comms port. For me it is vital to get/send data from the unit. Without it any integration is kind of crude.

Is the service the same when using bluetooth (except that you have to have another bluetooth device in range)?

**Comment by mattenausohz** [comment]
I got the API data from ECOFLOW for my Delta 2 and it works:

curl -X GET \
https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=XXXXX
-H 'Content-Type: application/json' \
-H 'appKey: xxx' \
-H 'secretKey: xxx'

It shows the following output:
object
code: "0"
message: "Success"
data: object
soc: 74
remainTime: -5939
wattsOutSum: 0
wattsInSum: 0

**Comment by raphaelsavina** [comment]
Have you that as well to integrate to HA (in confguration.yaml). You need to request appKey and secretKey from Ecoflow.
Please note that there is a bug with soc with an extra battery, the return value is only of the main one, not the average of the 2.

```
 - platform: rest
   unique_id: ecoflow_time_left
   unit_of_measurement: "min"
   device_class: duration
   name: Ecoflow Time Left
   resource: https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=xxx
   value_template: '{{ "%.1f" | format(value_json.data.remainTime)}}'
   method: GET
   headers:
     content_type:  'application/json'
     appKey: 'xxx'
     secretKey: 'xxx'

 - platform: rest
   unique_id: ecoflow_watt_out
   unit_of_measurement: "W"
   device_class: power
   name: Ecoflow Watt Out
   resource: https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=xxx
   value_template: '{{ "%.1f" | format(value_json.data.wattsOutSum)}}'
   method: GET
   headers:
     content_type:  'application/json'
     appKey: 'xxx'
     secretKey: 'xxx'

 - platform: rest
   unique_id: ecoflow_watt_in
   unit_of_measurement: "W"
   device_class: power
   name: Ecoflow Watt In
   resource: https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=xxx
   value_template: '{{ "%.1f" | format(value_json.data.wattsInSum)}}'
   method: GET
   headers:
     content_type:  'application/json'
     appKey: 'xxx'
     secretKey: 'xxx'

 - platform: rest
   unique_id: ecoflow_soc
   unit_of_measurement: "%"
   device_class: battery
   name: Ecoflow State of Charge
   resource: https://api.ecoflow.com/iot-service/open/api/device/queryDeviceQuota?sn=xxx
   value_template: '{{ "%.1f" | format(value_json.data.soc)}}'
   method: GET
   headers:
     content_type:  'application/json'
     appKey: 'xxx'
     secretKey: 'xxx'

```

How it looks (minutes have been converted to H:M:

![Screenshot 2022-10-17 at 09 42 48](https://user-images.githubusercontent.com/540382/196118154-b5722d74-59ec-4855-87b8-f67555007fd3.png)
